config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  devise_for :users

  resources :users, only: [:edit, :update] do
    resources :diaries do
      resources :comments, only: [:create, :edit, :update, :destroy]
    end

    resources :cart_products, only: [:create, :update, :destroy]
    resources :purchases, only: [:index, :show, :new, :create]
    resource :cart, only: [:show]
    resources :diary_images, only: [:index, :create, :destroy]
  end

  resources :products, only: [:index, :show]

  post 'likes/create'
  delete 'likes/destroy'
  get 'users/:id/remove_profile', to: "users#remove_profile", as: "users_remove_profile"

  namespace :admins do
    root to: 'home#index'
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :products
  end

end

app/models/cart_product.rb
class CartProduct < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product

  validates :cart_id, presence: true
  validates :product_id, presence: true
  validates_numericality_of :amount, greater_than_or_equal_to:0

  after_save :destroy_if_zero_amount

  private
  
  def destroy_if_zero_amount
    if amount == 0
      destroy
    end
  end
end

app/controllers/cart_products_controller.rb
# -*- coding: utf-8 -*-
class CartProductsController < ApplicationController

  before_action :sign_in_required
  before_action :current_user_required
  before_action :set_cart_and_product, only: [:update, :destroy]

  def create
    @cart = @user.cart
    @product = Product.find_by_id(params[:cart_product][:product_id])
    @cart_product = CartProduct.find_by_cart_id_and_product_id(@cart.id, @product.id)
    
    if @cart_product
      @cart_product.update(amount: @cart_product.amount + 1)
      redirect_to user_cart_url(@user), notice: "商品が追加されました" and return
    end

    @cart_product = CartProduct.new(cart_product_create_parmas)
    if @cart_product.save
      redirect_to user_cart_url(@user), notice: "商品が追加されました"
    else
      render "products/show"
    end
  end

  def update
    if @cart_product.update(cart_product_update_params)
      notice = @cart_product.amount == 0 ? "商品が削除されました" : "商品の数が更新されました"
      redirect_to user_cart_url(@user), notice: notice
    else
      render "carts/show"
    end
  end

  def destroy
    @cart_product.destroy
    redirect_to user_cart_url(@user), notice: "商品が削除されました"
  end

  private

  def cart_product_create_parmas
    params.require(:cart_product).permit(:cart_id, :product_id, :amount)
  end

  def cart_product_update_params
    params.require(:cart_product).permit(:amount)
  end

  def set_cart_and_product
    @cart_product = CartProduct.find_by_id(params[:id])
    @cart = @cart_product.cart
    @product = @cart_product.product
  end

end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/views/cart_products/_cart_product.html.haml
- product = cart_product.product
%tr
  %td= image_tag product.image.medium.url
  %td= product.name
  %td #{number_with_delimiter(product.price)}円
  - if defined? @editable
    %td
      = form_for [current_user, cart_product], role: "form", html: {method: :put} do |f|
        = f.number_field :amount
        = f.hidden_field :product_id, value: product.id
        個
    %td
      = link_to "更新", "#", role: "button", class:"btn btn-primary update-cart-product-button", id: "update-cart-product-#{cart_product.id}"
      = link_to "削除", user_cart_product_path(current_user, cart_product), method: :delete, data: { confirm: 'Are you sure?' }, role: "button", class:"btn btn-danger"
  - else
    %td #{cart_product.amount} 個

app/views/cart_products/create.html.haml
%h1 CartProducts#create
%p Find me in app/views/cart_products/create.html.haml

app/views/cart_products/update.html.haml
%h1 CartProducts#update
%p Find me in app/views/cart_products/update.html.haml