config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  devise_for :users

  resources :users, only: [:edit, :update] do
    resources :diaries do
      resources :comments, only: [:create, :edit, :update, :destroy]
    end

    resources :cart_products, only: [:create, :update, :destroy]
    resources :purchases, only: [:index, :show, :new, :create]
    resource :cart, only: [:show]
    resources :diary_images, only: [:index, :create, :destroy]
  end

  resources :products, only: [:index, :show]

  post 'likes/create'
  delete 'likes/destroy'
  get 'users/:id/remove_profile', to: "users#remove_profile", as: "users_remove_profile"

  namespace :admins do
    root to: 'home#index'
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :products
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_products
  has_many :products, through: :cart_products

  def product_count
    cart_products.pluck(:amount).inject(&:+)    
  end

  def product_price
    total = 0
    cart_products.find_each do |cart_product|
      unit_price = cart_product.product.price
      total += unit_price * cart_product.amount
    end
    total
  end

  def shipping_cost
    product_count = cart_products.map {|cart_product| cart_product.amount}.inject(&:+)
    600 * ((product_count - 1) / 5 + 1)
  end

  def cash_on_delivery
    case product_price
    when 0...10000 then 300 
    when 10000...30000 then 400
    when 30000...100000 then 600
    else 1000
    end
  end

  def total_without_tax
    product_price + shipping_cost + cash_on_delivery
  end

  def tax_percentage
    8
  end

  def tax
    total_without_tax  * tax_percentage / 100
  end

  def total_price_with_tax
    total_without_tax + tax
  end

  def do_purchase(purchase)
    transaction do
      cart_products.find_each do |cart_product|
        @product = cart_product.product;
        purchase.purchase_products.create(
          product_id: @product.id,
          amount: cart_product.amount
        )
      end
      cart_products.destroy_all
    end
    true
  rescue
    purchase.destroy
    false
  end

  
end

app/models/cart_product.rb
class CartProduct < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product

  validates :cart_id, presence: true
  validates :product_id, presence: true
  validates_numericality_of :amount, greater_than_or_equal_to:0

  after_save :destroy_if_zero_amount

  private
  
  def destroy_if_zero_amount
    if amount == 0
      destroy
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :diary
  belongs_to :commenter, class_name: "User"

  validates :body, presence: true

  def htmlized_body
    "<div>#{body}</div>".gsub("\n", "<br />").html_safe
  end
  
end

app/models/diary.rb
class Diary < ActiveRecord::Base

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :user_id, presence: true

  default_scope { order(created_at: :desc) }

  paginates_per 10

  def htmlized_body
    "<div>#{body}</div>".gsub("\n", "<br />").html_safe
  end

end

app/models/diary_image.rb
class DiaryImage < ActiveRecord::Base
  belongs_to :user

  validates :user_id, presence: true

  mount_uploader :image, DiaryImageUploader
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :diary
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_paper_trail

  has_many :cart_products
  has_many :carts, through: :cart_products
  has_many :purchase_products
  
  validates :name, presence: true
  validates :image, presence: true
  validates :description, presence: true
  validates_numericality_of :price, greater_than_or_equal_to:0
  validates_numericality_of :display_order, greater_than_or_equal_to:0

  scope :sorted, -> {
    order(:display_order)
  }
  
  scope :valid, -> {
    where(hidden: false)
  } 

  mount_uploader :image, UploaderBase

  paginates_per 40

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  include MultiStepModel
  extend Enumerize

  belongs_to :user
  has_many :purchase_products, dependent: :destroy

  validates :ship_name, presence: true, :if => :step1?
  validates :ship_address, presence: true, :if => :step1?
  validates :ship_zip_code, presence: true, :if => :step1?

  enumerize :delivery_time, in: [:t_8_12, :t_12_14, :t_14_16, :t_16_18, :t_18_20, :t_20_21], default: :t_8_12

  default_scope {order(:created_at => :desc)}
  
  def self.total_steps
    3
  end

  def delivery_date_options
    (3.weekdays_from_now.to_date..14.weekdays_from_now.to_date).to_a.select{|date| date.weekday?}    
  end

  def total_without_tax
    product_price + shipping_cost + cash_on_delivery
  end
  
  def total_price_with_tax
    total_without_tax * (100 + tax_percentage) / 100
  end

  def tax
    total_without_tax * tax_percentage / 100
  end

  def purchased_at
    created_at.localtime.strftime("%Y/%m/%d %H:%M")
  end
  
end

app/models/purchase_product.rb
class PurchaseProduct < ActiveRecord::Base
  belongs_to :purchase
  belongs_to :product

  validates :purchase_id, presence: true
  validates :product_id, presence: true
  validates_numericality_of :amount, greater_than_or_equal_to:0

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :name, presence: true

  has_many :diaries, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_diaries, through: :likes, source: :diary
  has_many :comments, foreign_key: "commenter_id", dependent: :destroy
  has_one :cart, dependent: :destroy
  has_many :purchases
  has_many :diary_images, dependent: :destroy

  mount_uploader :profile_image, UploaderBase

  after_create :create_cart_if_not_exists

  def small_profile
    if profile_image?
      profile_image.small.url
    else
      ActionController::Base.helpers.asset_path("defaults/profile_small.png")
    end
  end

  def medium_profile
    if profile_image?
      profile_image.medium.url
    else
      ActionController::Base.helpers.asset_path("defaults/profile_medium.png")
    end
  end

  private

  def create_cart_if_not_exists
    create_cart unless cart
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = current_user
    @diaries = Diary.page(params[:page])
  end
end

app/controllers/purchases_controller.rb
# -*- coding: utf-8 -*-
class PurchasesController < ApplicationController

  before_action :sign_in_required, :current_user_required
  before_action :load_wizard, only: [:new, :create]
  
  def index
    @purchases = @user.purchases.page(params[:page])
  end

  def show
    @purchase = @user.purchases.find_by_id(params[:id])
  end

  def new
    @purchase = @wizard.object
  end

  def create
    @purchase = @wizard.object
    if @wizard.save and @user.cart.do_purchase(@purchase)
      redirect_to [@user, @purchase], notice: "購入手続きが完了しました"
    else
      render :new
    end
  end

  private

  def load_wizard
    @wizard = ModelWizard.new(@user.purchases.new, session, params)
    if self.action_name.in? %w[new]
      @wizard.start
    elsif self.action_name.in? %w[create]
      @wizard.process
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/diary_images_helper.rb
module DiaryImagesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def link_to_user(user, display_text = nil)
    link_to (display_text || user.name), user_diaries_path(user)
  end
end

app/views/purchases/_confirm.html.haml
%h2 確認

%table.table.table-striped
  = render current_user.cart.cart_products
.col-xs-6
  = render partial: "carts/cart_info", locals: {cart: current_user.cart}

app/views/purchases/_form.html.haml
- if @purchase.last_step?
  = render "confirm"

= form_for [current_user, @purchase], role: "form", html:{ method: :post, class: "col-xs-12"} do |f|
  = render partial: "error_messages", locals:{object: @purchase}
  = f.hidden_field :current_step, value: @purchase.current_step
  = render "purchases/steps/page#{@purchase.current_step+1}", f: f

  .form-group
    = f.submit "戻る", name: "back_button", class:"btn btn-default" unless @purchase.first_step?
    - if @purchase.last_step?
      = f.submit "購入する", class:"btn btn-primary btn-lg"
    - else
      = f.submit "次へ", class:"btn btn-primary btn-lg"
        

app/views/purchases/_purchase.html.haml
%li
  - url = user_purchase_path(@user, purchase)
  .row
    .col-xs-3
      = link_to "#{purchase.purchased_at}のお買い物", url
    .col-xs-3= "#{number_with_delimiter(purchase.total_price_with_tax)}円"

app/views/purchases/_purchase_info.html.haml
%table.table
  %tr
    %td 商品計
    %td #{number_with_delimiter(purchase.product_price)} 円
  %tr
    %td 送料
    %td #{number_with_delimiter(purchase.shipping_cost)} 円
  %tr
    %td 代引き手数料
    %td #{number_with_delimiter(purchase.cash_on_delivery)} 円
  %tr
    %td 小計
    %td #{number_with_delimiter(purchase.total_without_tax)} 円
  %tr
    %td 消費税
    %td #{number_with_delimiter(purchase.tax)} 円
  %tr
    %td 合計
    %td #{number_with_delimiter(purchase.total_price_with_tax)} 円

app/views/purchases/confirm.html.haml
%h1 Purchases#confirm
%p Find me in app/views/purchases/confirm.html.haml

app/views/purchases/create.html.haml
%h1 Purchases#create
%p Find me in app/views/purchases/create.html.haml

app/views/purchases/index.html.haml
%h1 購入履歴

%ul.plain-list
  = render @purchases

= paginate @purchases, theme: "twitter-bootstrap-3"  

app/views/purchases/new.html.haml
%h1= "ご購入手続き(#{@purchase.current_step+1}/3)"

= render "form"

app/views/purchases/show.html.haml
= link_to "購入履歴へ", user_purchases_path(@user), role: "button", class: "btn btn-primary"

%h1= "#{@purchase.purchased_at}のお買い物"

%table.table.table-striped
  = render @purchase.purchase_products
.col-xs-6
  = render partial: "purchases/purchase_info", locals: {purchase: @purchase}

  