config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  devise_for :users

  resources :users, only: [:edit, :update] do
    resources :diaries do
      resources :comments, only: [:create, :edit, :update, :destroy]
    end

    resources :cart_products, only: [:create, :update, :destroy]
    resources :purchases, only: [:index, :show, :new, :create]
    resource :cart, only: [:show]
    resources :diary_images, only: [:index, :create, :destroy]
  end

  resources :products, only: [:index, :show]

  post 'likes/create'
  delete 'likes/destroy'
  get 'users/:id/remove_profile', to: "users#remove_profile", as: "users_remove_profile"

  namespace :admins do
    root to: 'home#index'
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :products
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates :name, presence: true

  has_many :diaries, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_diaries, through: :likes, source: :diary
  has_many :comments, foreign_key: "commenter_id", dependent: :destroy
  has_one :cart, dependent: :destroy
  has_many :purchases
  has_many :diary_images, dependent: :destroy

  mount_uploader :profile_image, UploaderBase

  after_create :create_cart_if_not_exists

  def small_profile
    if profile_image?
      profile_image.small.url
    else
      ActionController::Base.helpers.asset_path("defaults/profile_small.png")
    end
  end

  def medium_profile
    if profile_image?
      profile_image.medium.url
    else
      ActionController::Base.helpers.asset_path("defaults/profile_medium.png")
    end
  end

  private

  def create_cart_if_not_exists
    create_cart unless cart
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < Admins::ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @users = User.all.page(params[:page])
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to admins_user_url(@user)
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admins_users_url
  end

  private

  def set_user
    @user = User.find_by_id(params[:id])
  end

  def user_params
    attributes = %I(email name ship_name ship_zip_code ship_address)
    params.require(:user).permit(attributes)
  end

end

app/controllers/users_controller.rb
# -*- coding: utf-8 -*-
class UsersController < ApplicationController

  before_action :sign_in_required, :set_and_check_user
  
  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to edit_user_url(@user), notice: "ユーザー情報を更新しました"
    else
      render :edit
    end
  end

  def remove_profile
    @user.remove_profile_image!
    @user.save
    redirect_to edit_user_url(@user), notice: "プロフィール画像を削除しました"
  end

  private

  def user_params
    params.require(:user).permit(:name, :ship_name, :ship_zip_code, :ship_address, :profile_image)
  end

  def set_and_check_user
    @user = User.find_by_id(params[:id])
    redirect_to new_user_session_url if @user.id != current_user.id
  end
  
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def link_to_user(user, display_text = nil)
    link_to (display_text || user.name), user_diaries_path(user)
  end
end

app/views/admins/users/_user.html.haml
%tr
  %td= user.email
  %td= user.name
  %td
    = link_to "詳細を見る", admins_user_path(user)
  %td
    = link_to "編集", edit_admins_user_path(user), class: "btn btn-primary", role: "button"
    = link_to "削除", admins_user_path(user), class: "btn btn-danger", role: "button", method: :delete, data: {confirm: "Are you sure?"}

app/views/admins/users/destroy.html.haml
%h1 Admins::Users#destroy
%p Find me in app/views/admins/users/destroy.html.haml

app/views/admins/users/edit.html.haml
%h1 ユーザー情報の変更

= form_for(@user, url: admins_user_path(@user), html:{method: :put, role: "form", class: "col-xs-6"}) do |f|
  = render partial: "error_messages", locals:{object:@user}
  .form-group
    = f.label :email, "Eメール"
    = f.email_field :email, class:"form-control"
  - if Devise.mappings[:user].confirmable? && @user.pending_reconfirmation?
    .form-control
      メールアドレス #{@user.unconfirmed_email} が確認できていません。
  .form-group
    = f.label :name, "ニックネーム"
    = f.text_field :name, :autofocus => true, class:"form-control"
  .form-group
    = f.label :ship_name, "配送先お名前"
    = f.text_field :ship_name, class:"form-control"
  .form-group
    = f.label :ship_zip_code, "郵便番号"
    = f.text_field :ship_zip_code, class:"form-control"
  .form-group
    = f.label :ship_address, "ご住所"
    = f.text_field :ship_address, class:"form-control"
  .form-group
    = link_to "戻る", :back, role: "button", class: "btn btn-default"
    = f.submit "更新", class:"btn btn-primary"
 

app/views/admins/users/index.html.haml
%h1 ユーザー管理

= paginate @users, theme: "twitter-bootstrap-3"

%table.table.table-striped
  %tr
    %th メールアドレス
    %th 表示名
    %th  
    %th  
  = render @users

= paginate @users, theme: "twitter-bootstrap-3"

app/views/admins/users/show.html.haml
%h1= "ユーザー#{@user.id}の情報"

%div
  = link_to "編集", edit_admins_user_path(@user), class: "btn btn-primary", role: "button"
  = link_to "削除", admins_user_path(@user), class: "btn btn-danger", role: "button", method: :delete, data: {confirm: "Are you sure?"}

%table.table.table-condensed
  - User.column_names.each_with_index do |name, idx|
    %tr
      %td= name
      %td
        - if name == "profile_image"
          = @user.profile_image? ? image_tag(@user.profile_image.small.url) : ""
        - else
          = @user.attributes.values[idx]

app/views/admins/users/update.html.haml
%h1 Admins::Users#update
%p Find me in app/views/admins/users/update.html.haml